from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KNN(object):
    def setupUi(self, KNN):
        KNN.setObjectName("KNN")
        KNN.setFixedSize(352, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KNN.setWindowIcon(icon)
        KNN.setStyleSheet("border-image: url(:/images/BackGround.jpg);")
        self.gridLayout = QtWidgets.QGridLayout(KNN)
        self.gridLayout.setObjectName("gridLayout")
        self.algorithmlist = QtWidgets.QComboBox(KNN)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.algorithmlist.setFont(font)
        self.algorithmlist.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.algorithmlist.setObjectName("algorithmlist")
        self.algorithmlist.addItem("")
        self.algorithmlist.addItem("")
        self.algorithmlist.addItem("")
        self.algorithmlist.addItem("")
        self.gridLayout.addWidget(self.algorithmlist, 1, 1, 1, 2)
        self.p = QtWidgets.QLabel(KNN)
        self.p.setStyleSheet("border-image: url(:/images/1WhiteTransparent.png);")
        self.p.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.p.setObjectName("p")
        self.gridLayout.addWidget(self.p, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        self.weights = QtWidgets.QLabel(KNN)
        self.weights.setStyleSheet("border-image: url(:/images/1WhiteTransparent.png);")
        self.weights.setAlignment(QtCore.Qt.AlignCenter)
        self.weights.setObjectName("weights")
        self.gridLayout.addWidget(self.weights, 0, 3, 1, 3)
        self.n_neighbors = QtWidgets.QLabel(KNN)
        self.n_neighbors.setStyleSheet("border-image: url(:/images/1WhiteTransparent.png);")
        self.n_neighbors.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.n_neighbors.setObjectName("n_neighbors")
        self.gridLayout.addWidget(self.n_neighbors, 5, 2, 1, 2)
        self.algorithm = QtWidgets.QLabel(KNN)
        self.algorithm.setStyleSheet("border-image: url(:/images/1WhiteTransparent.png);")
        self.algorithm.setScaledContents(True)
        self.algorithm.setAlignment(QtCore.Qt.AlignCenter)
        self.algorithm.setObjectName("algorithm")
        self.gridLayout.addWidget(self.algorithm, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 6, 1, 1)
        self.pspinBox = QtWidgets.QSpinBox(KNN)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pspinBox.setFont(font)
        self.pspinBox.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.pspinBox.setMaximum(100)
        self.pspinBox.setProperty("value", 2)
        self.pspinBox.setObjectName("pspinBox")
        self.gridLayout.addWidget(self.pspinBox, 3, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 4, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(52, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 2, 4, 1, 1)
        self.n_neighborsspinBox = QtWidgets.QSpinBox(KNN)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_neighborsspinBox.setFont(font)
        self.n_neighborsspinBox.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.n_neighborsspinBox.setMaximum(100)
        self.n_neighborsspinBox.setProperty("value", 5)
        self.n_neighborsspinBox.setObjectName("n_neighborsspinBox")
        self.gridLayout.addWidget(self.n_neighborsspinBox, 5, 5, 1, 1)
        self.weightslist = QtWidgets.QComboBox(KNN)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weightslist.setFont(font)
        self.weightslist.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.weightslist.setObjectName("weightslist")
        self.weightslist.addItem("")
        self.weightslist.addItem("")
        self.gridLayout.addWidget(self.weightslist, 1, 3, 1, 3)
        self.leaf_size = QtWidgets.QLabel(KNN)
        self.leaf_size.setStyleSheet("border-image: url(:/images/1WhiteTransparent.png);")
        self.leaf_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.leaf_size.setObjectName("leaf_size")
        self.gridLayout.addWidget(self.leaf_size, 4, 2, 1, 1)
        self.leaf_sizespinBox = QtWidgets.QSpinBox(KNN)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leaf_sizespinBox.setFont(font)
        self.leaf_sizespinBox.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.leaf_sizespinBox.setMinimum(0)
        self.leaf_sizespinBox.setMaximum(100)
        self.leaf_sizespinBox.setProperty("value", 30)
        self.leaf_sizespinBox.setObjectName("leaf_sizespinBox")
        self.gridLayout.addWidget(self.leaf_sizespinBox, 4, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 6, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(141, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 7, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Restore = QtWidgets.QDialogButtonBox(KNN)
        self.Restore.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.Restore.setOrientation(QtCore.Qt.Horizontal)
        self.Restore.setStandardButtons(QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.Restore.setCenterButtons(True)
        self.Restore.setObjectName("Restore")
        self.horizontalLayout.addWidget(self.Restore)
        self.Cancel = QtWidgets.QDialogButtonBox(KNN)
        self.Cancel.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.Cancel.setOrientation(QtCore.Qt.Horizontal)
        self.Cancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.Cancel.setCenterButtons(True)
        self.Cancel.setObjectName("Cancel")
        self.horizontalLayout.addWidget(self.Cancel)
        self.Apply = QtWidgets.QDialogButtonBox(KNN)
        self.Apply.setStyleSheet("border-image: url(:/images/1WhiteBackground.jpg);")
        self.Apply.setOrientation(QtCore.Qt.Horizontal)
        self.Apply.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
        self.Apply.setCenterButtons(True)
        self.Apply.setObjectName("Apply")
        self.horizontalLayout.addWidget(self.Apply)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 3, 1, 4)

        self.retranslateUi(KNN)
        self.Cancel.accepted.connect(KNN.accept)
        self.Cancel.rejected.connect(KNN.reject)
        QtCore.QMetaObject.connectSlotsByName(KNN)
        
        self.Restore.clicked.connect(self.reset)

    def reset(self):
        self.algorithmlist.setCurrentIndex(0)
        self.weightslist.setCurrentIndex(0)
        self.pspinBox.setValue(2)
        self.leaf_sizespinBox.setValue(30)
        self.n_neighborsspinBox.setValue(5)
        

    def retranslateUi(self, KNN):
        _translate = QtCore.QCoreApplication.translate
        KNN.setWindowTitle(_translate("KNN", "KNN"))
        self.algorithmlist.setItemText(0, _translate("KNN", "auto"))
        self.algorithmlist.setItemText(1, _translate("KNN", "ball_tree"))
        self.algorithmlist.setItemText(2, _translate("KNN", "kd_tree"))
        self.algorithmlist.setItemText(3, _translate("KNN", "brute"))
        self.p.setText(_translate("KNN", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">P</span></p></body></html>"))
        self.weights.setText(_translate("KNN", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">Weights</span></p></body></html>"))
        self.n_neighbors.setText(_translate("KNN", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">N_neighbors</span></p></body></html>"))
        self.algorithm.setText(_translate("KNN", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">Algorithm</span></p></body></html>"))
        self.weightslist.setItemText(0, _translate("KNN", "uniform"))
        self.weightslist.setItemText(1, _translate("KNN", "distance"))
        self.leaf_size.setText(_translate("KNN", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">Leaf_size</span></p></body></html>"))
import Images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    KNN = QtWidgets.QDialog()
    ui = Ui_KNN()
    ui.setupUi(KNN)
    KNN.show()
    sys.exit(app.exec_())
